package org.example;

public enum CommandsType {
    AUTH, AUTH_OK, AUTH_ERR, PRIVATE_MSG, PUBLIC_MSG, INFO_MSG, ERROR, UPDATE_USERS, END, ADD_USER, CHANGE_NICK, UPDATE_LIST_CLIENTS, GET_USERS, SEND_USERS
}
